// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSW_J_mu9ipuZ_HGD6DBxSWKKEF_GTT_4',
    appId: '1:199420111901:web:5f35763a904c018770aaf4',
    messagingSenderId: '199420111901',
    projectId: 'recycle-appp',
    authDomain: 'recycle-appp.firebaseapp.com',
    storageBucket: 'recycle-appp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbEu0-cJqy7NzMod6msR8MsSWvhcQXBX0',
    appId: '1:199420111901:android:0e432f0b9318e53370aaf4',
    messagingSenderId: '199420111901',
    projectId: 'recycle-appp',
    storageBucket: 'recycle-appp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNq9CWAzLLfX7L0zTaLkOCszYFX49cKhc',
    appId: '1:199420111901:ios:ac50fa0186ae3a9870aaf4',
    messagingSenderId: '199420111901',
    projectId: 'recycle-appp',
    storageBucket: 'recycle-appp.appspot.com',
    iosBundleId: 'com.example.recycleAppHackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNq9CWAzLLfX7L0zTaLkOCszYFX49cKhc',
    appId: '1:199420111901:ios:ac50fa0186ae3a9870aaf4',
    messagingSenderId: '199420111901',
    projectId: 'recycle-appp',
    storageBucket: 'recycle-appp.appspot.com',
    iosBundleId: 'com.example.recycleAppHackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSW_J_mu9ipuZ_HGD6DBxSWKKEF_GTT_4',
    appId: '1:199420111901:web:e33f3b7e168e4ea070aaf4',
    messagingSenderId: '199420111901',
    projectId: 'recycle-appp',
    authDomain: 'recycle-appp.firebaseapp.com',
    storageBucket: 'recycle-appp.appspot.com',
  );
}
